/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author MY COMP
 */
public class JodohDiTanganTuhan extends javax.swing.JFrame {

    /**
     * Creates new form JodohDiTanganTuhan
     */
    public JodohDiTanganTuhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        NamaCalon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Agama = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        R11 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        R12 = new javax.swing.JRadioButton();
        R13 = new javax.swing.JRadioButton();
        R14 = new javax.swing.JRadioButton();
        R15 = new javax.swing.JRadioButton();
        R21 = new javax.swing.JRadioButton();
        R22 = new javax.swing.JRadioButton();
        R25 = new javax.swing.JRadioButton();
        R24 = new javax.swing.JRadioButton();
        R23 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Calon");

        NamaCalon.setBackground(new java.awt.Color(255, 153, 153));
        NamaCalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaCalonActionPerformed(evt);
            }
        });

        jLabel2.setText("Agama");

        Agama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Katolik", "Protestan", "Buddha", "Hindu", "Konghucu" }));
        Agama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgamaActionPerformed(evt);
            }
        });

        jLabel3.setText("1.Paras Wajah");

        R11.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(R11);
        R11.setText("1");

        jLabel4.setText("2.Tingkah Laku");

        R12.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(R12);
        R12.setText("2");
        R12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R12ActionPerformed(evt);
            }
        });

        R13.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(R13);
        R13.setText("3");
        R13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R13ActionPerformed(evt);
            }
        });

        R14.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(R14);
        R14.setText("4");
        R14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R14ActionPerformed(evt);
            }
        });

        R15.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(R15);
        R15.setText("5");

        R21.setBackground(new java.awt.Color(255, 140, 140));
        buttonGroup2.add(R21);
        R21.setText("1");
        R21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R21ActionPerformed(evt);
            }
        });

        R22.setBackground(new java.awt.Color(255, 140, 140));
        buttonGroup2.add(R22);
        R22.setText("2");
        R22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R22ActionPerformed(evt);
            }
        });

        R25.setBackground(new java.awt.Color(255, 140, 140));
        buttonGroup2.add(R25);
        R25.setText("5");
        R25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R25ActionPerformed(evt);
            }
        });

        R24.setBackground(new java.awt.Color(255, 140, 140));
        buttonGroup2.add(R24);
        R24.setText("4");
        R24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R24ActionPerformed(evt);
            }
        });

        R23.setBackground(new java.awt.Color(255, 140, 140));
        buttonGroup2.add(R23);
        R23.setText("3");
        R23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R23ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Hasil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Hasil.setBackground(new java.awt.Color(255, 204, 204));
        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("JODOHKU DITANGAN TUHAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(R14)
                                    .addGap(18, 18, 18)
                                    .addComponent(R15))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Agama, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(126, 126, 126)
                                                    .addComponent(jButton1)))
                                            .addGap(51, 51, 51))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(R11)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(R12)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(R13))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(48, 48, 48)
                                                    .addComponent(R21)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(R22)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(R23)))
                                            .addGap(25, 25, 25)))
                                    .addComponent(R24)
                                    .addGap(18, 18, 18)
                                    .addComponent(R25))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NamaCalon, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NamaCalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R15)
                    .addComponent(R14)
                    .addComponent(R13)
                    .addComponent(R12)
                    .addComponent(R11)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R25)
                    .addComponent(R24)
                    .addComponent(R23)
                    .addComponent(R22)
                    .addComponent(R21)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R25ActionPerformed

    private void NamaCalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaCalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaCalonActionPerformed

    private void AgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgamaActionPerformed

    private void R14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R14ActionPerformed

    private void R22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R22ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Nama  = NamaCalon.getText();
        String Religi = (String)Agama.getSelectedItem();
        String keputusan ="";
        float nilai = 0;
        if (R11.isSelected()){
        nilai = 1;
        }
        else if  (R12.isSelected()){
        nilai = 2;
        }
        else if (R13.isSelected()){
        nilai = 3;
        }
        else if (R14.isSelected()){
        nilai = 4;
        }
        else if (R15.isSelected()){
        nilai = 5;
        }
        
        float nilai1 = 0;
        if (R21.isSelected()){
        nilai1 = 1;
        }
        else if  (R22.isSelected()){
        nilai1 = 2;
        }
        else if (R23.isSelected()){
        nilai1 = 3;
        }
        else if (R24.isSelected()){
        nilai1 = 4;
        }
        else if (R25.isSelected()){
        nilai1 = 5;
        }
        
        float cek = (nilai+nilai1)/2;
        if (cek >= 4.5){
            keputusan = "Sangat Recommended menjadi pasangan hidup";
        }
        else if  (cek >= 3.5){
            keputusan = "Recommended menjadi pasangan hidup";
        }
        else if (cek >= 2.5){
            keputusan = "Cukup Recommended menjadi pasangan hidup";
        }
        else if (cek >= 1.5){
            keputusan = "Kurang Recommended menjadi pasangan hidup";
        }
            else {
            keputusan = "Tidak Recommended menjadi pasangan hidup";
        }
        Hasil.setText("Nama Calon \t: " + Nama + "\nAgama\t: "+Religi+ "\nHasil\t:"+keputusan);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void R23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R23ActionPerformed

    private void R21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R21ActionPerformed

    private void R24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R24ActionPerformed

    private void R13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R13ActionPerformed

    private void R12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JodohDiTanganTuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JodohDiTanganTuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JodohDiTanganTuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JodohDiTanganTuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JodohDiTanganTuhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Agama;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JTextField NamaCalon;
    private javax.swing.JRadioButton R11;
    private javax.swing.JRadioButton R12;
    private javax.swing.JRadioButton R13;
    private javax.swing.JRadioButton R14;
    private javax.swing.JRadioButton R15;
    private javax.swing.JRadioButton R21;
    private javax.swing.JRadioButton R22;
    private javax.swing.JRadioButton R23;
    private javax.swing.JRadioButton R24;
    private javax.swing.JRadioButton R25;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
